import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const src=fs.readFileSync(new URL('../assets/app.js',import.meta.url),'utf8');
const writes=[];let sequence=0;
const context={uid:()=>String(++sequence),state:{settings:{activeProjectId:'p1'}},activeChatId:'c1',currentHarnessRun:null,currentChangeSet:null,structuredClone,Date,Math,idbPut:async(store,value)=>writes.push({store,value:structuredClone(value)})};
vm.createContext(context);
vm.runInContext(src.slice(src.indexOf('async function appendSessionEvent('),src.indexOf('function lineDiff(')),context);
await context.createHarnessRun('Council session');
assert.equal(context.currentHarnessRun.chatId,'c1');
assert.equal(context.currentHarnessRun.projectId,'p1');
assert.equal(context.currentHarnessRun.status,'planning');
assert(writes.some(x=>x.store==='sessionevents'&&x.value.type==='run.started'));
await context.updateHarnessRun({phase:'working'});
assert.equal(context.currentHarnessRun.phase,'working');
await context.finishHarnessRun('done',{answerMessageId:'answer-1'});
assert.equal(context.currentHarnessRun.status,'done');
assert.equal(context.currentHarnessRun.answerMessageId,'answer-1');
assert(context.currentHarnessRun.finishedAt);
assert(!writes.some(x=>x.store==='changesets'),'read-only discussion must not persist a changeset');
await context.createHarnessRun('Failure');await context.finishHarnessRun('failed',{error:'provider error'});
assert.equal(context.currentHarnessRun.status,'failed');
assert(writes.some(x=>x.store==='sessionevents'&&x.value.type==='run.finished'&&x.value.payload.status==='failed'));
console.log('harness runtime: run lifecycle, chat scope, events and read-only changesets passed');
